#!/usr/bin/env python3
"""Fetch Apify actor metadata (no Actor runs) and write a safe input-schema audit.

Reads ``APIFY_TOKEN`` / ``APIFY_TOKEN_N`` from ``.env``. Never prints token values.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

import requests
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
os.chdir(ROOT)
load_dotenv(ROOT / ".env", override=False)

from finfluencer_alpha.x_apify_provider_registry import (  # noqa: E402
    all_provider_keys,
    build_canary_actor_input,
    get_provider,
)
from finfluencer_alpha.x_youtube_pipeline import (  # noqa: E402
    APIFY_BASE_URL,
    _apify_headers,
    _extract_data,
)

OUT = ROOT / "data/exports/overnight_collection/37_x_apify_actor_input_schema_audit.md"


def _first_apify_token() -> str:
    count_raw = os.getenv("APIFY_TOKEN_COUNT", "0").strip() or "0"
    try:
        n = int(count_raw)
    except ValueError:
        n = 0
    for i in range(1, max(n, 0) + 1):
        tok = os.getenv(f"APIFY_TOKEN_{i}", "").strip()
        if tok:
            return tok
    tok = os.getenv("APIFY_TOKEN", "").strip()
    if tok:
        return tok
    raise RuntimeError("No APIFY_TOKEN or APIFY_TOKEN_N in environment")


def _normalize_actor_id(actor_id: str) -> str:
    return actor_id.replace("/", "~")


def fetch_actor(actor_id: str, token: str) -> dict[str, Any]:
    url = f"{APIFY_BASE_URL}/acts/{_normalize_actor_id(actor_id)}"
    response = requests.get(url, headers=_apify_headers(token), timeout=120)
    if response.status_code >= 400:
        return {"_error": f"HTTP_{response.status_code}", "actor_id": actor_id}
    return _extract_data(response.json())


def _schema_field_names(schema: Any) -> tuple[list[str], list[str]]:
    required: list[str] = []
    names: list[str] = []
    if not isinstance(schema, dict):
        return names, required
    req = schema.get("required")
    if isinstance(req, list):
        required = [str(x) for x in req if isinstance(x, str)]
    props = schema.get("properties")
    if isinstance(props, dict):
        names = sorted(str(k) for k in props.keys())
    return names, required


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--actor-id", action="append", dest="actor_ids", default=[])
    args = parser.parse_args()
    actor_ids = list(args.actor_ids)
    if not actor_ids:
        actor_ids = [get_provider(k).actor_id for k in all_provider_keys()]

    token = _first_apify_token()
    lines: list[str] = [
        "# X Apify actor input schema audit",
        "",
        "Generated by `scripts/discover_x_apify_actor_inputs.py` (metadata GET only; no Actor runs).",
        "",
    ]

    for actor_id in actor_ids:
        data = fetch_actor(actor_id, token)
        lines.append(f"## `{actor_id}`")
        lines.append("")
        if "_error" in data:
            lines.append(f"- **Fetch:** failed ({data['_error']})")
            lines.append("")
            continue
        lines.append("- **Metadata fetched:** yes")
        name = str(data.get("name") or "")
        title = str(data.get("title") or "")
        if name or title:
            lines.append(f"- **Listing name:** `{name or title}`")
        stats = data.get("stats") if isinstance(data.get("stats"), dict) else {}
        if stats:
            lines.append(
                "- **Stats (Apify):** "
                + json.dumps(
                    {k: stats.get(k) for k in ("totalRuns", "totalUsers", "totalBuilds") if k in stats},
                    indent=0,
                )
            )
        pricing = data.get("pricingInfos") or data.get("pricing")
        if pricing is not None:
            lines.append("- **Pricing info present:** yes (details omitted; see Apify console)")
        else:
            lines.append("- **Pricing info present:** not in payload summary")

        input_schema = data.get("inputSchema") or data.get("inputBody") or {}
        if isinstance(input_schema, dict) and "schema" in input_schema:
            input_schema = input_schema.get("schema") or input_schema
        field_names, required = _schema_field_names(input_schema if isinstance(input_schema, dict) else {})
        lines.append("")
        lines.append("### Input schema fields (best-effort)")
        lines.append("")
        if field_names:
            lines.append("```json")
            lines.append(json.dumps({"fields": field_names, "required": required}, indent=2))
            lines.append("```")
        else:
            lines.append("_No `properties` list extracted; actor may use free-form JSON input._")

        sample_entry = {
            "label": "schema_probe",
            "query": "from:ThePlainBagel $TSLA since:2020-02-18 until:2020-02-24 lang:en",
            "ticker": "TSLA",
            "since": "2020-02-18",
            "until": "2020-02-24",
            "handle_audit": "CHANNEL_X needle: plain bagel -> ThePlainBagel",
        }
        proposed: dict[str, Any] = {}
        for pk in all_provider_keys():
            if get_provider(pk).actor_id == actor_id:
                proposed = build_canary_actor_input(pk, sample_entry, 5)
                break
        lines.append("")
        lines.append("### Proposed canary input (pipeline `build_x_actor_input`, `advanced_search`)")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(proposed, indent=2) if proposed else "{}")
        lines.append("```")
        q = sample_entry["query"]
        adv = "from:" in q and "since:" in q and "$" in q
        lines.append("")
        lines.append(f"- **Advanced search query shape in probe:** {'yes' if adv else 'unknown'}")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        rel = OUT.relative_to(ROOT)
    except ValueError:
        rel = OUT
    print(f"wrote {rel}")


if __name__ == "__main__":
    main()
